### ISSUE TITLE
potential mess with GFW_HuntersHelper

### ISSUE THREAD

**Issue by TortugaModding** [pellevink/HunterHelper#10]
Hi! There's another addon named GFW_HuntersHelper (basically, a database of pet skills) which also uses `/hh` command. Since that one is discontinued (see http://fizzwidget.com/discontinued), but is still used on 1.12.1, maybe you'd consider amending yours, in order to make them able to work together

**Comment by pellevink** [comment]
Good catch. Will adjust

**Comment by pellevink** [comment]
fixed in #11
